// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idgenapi.Database;

#nullable disable

namespace idgenapi.Migrations
{
    [DbContext(typeof(IdGenApiContext))]
    partial class IdGenApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("idgenapi.IdGeneratedFeature.IdGenerated", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdon");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnName("serverip");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("servername");

                    b.Property<string>("UUIDString")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("uuidstring");

                    b.Property<string>("UlidString")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("ulidstring");

                    b.HasKey("Id");

                    b.ToTable("idsgenerated", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
